# coding: utf-8

"""
    RMA Service

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v1
    Contact: info@gemini-commerce.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from rma.models.rma_sort_order import RmaSortOrder

class TestRmaSortOrder(unittest.TestCase):
    """RmaSortOrder unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testRmaSortOrder(self):
        """Test RmaSortOrder"""
        # inst = RmaSortOrder()

if __name__ == '__main__':
    unittest.main()
