# coding: utf-8

"""
    RMA Service

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v1
    Contact: info@gemini-commerce.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from rma.models.rma_edit_note_request import RmaEditNoteRequest

class TestRmaEditNoteRequest(unittest.TestCase):
    """RmaEditNoteRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RmaEditNoteRequest:
        """Test RmaEditNoteRequest
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RmaEditNoteRequest`
        """
        model = RmaEditNoteRequest()
        if include_optional:
            return RmaEditNoteRequest(
                tenant_id = '',
                id = '',
                payload = rma.models.edit_note_request_payload.EditNoteRequestPayload(
                    author = '', 
                    note = '', ),
                payload_mask = ''
            )
        else:
            return RmaEditNoteRequest(
                tenant_id = '',
                id = '',
        )
        """

    def testRmaEditNoteRequest(self):
        """Test RmaEditNoteRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
