# coding: utf-8

"""
    RMA Service

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v1
    Contact: info@gemini-commerce.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from rma.models.order_data_subtotal_code import OrderDataSubtotalCode

class TestOrderDataSubtotalCode(unittest.TestCase):
    """OrderDataSubtotalCode unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testOrderDataSubtotalCode(self):
        """Test OrderDataSubtotalCode"""
        # inst = OrderDataSubtotalCode()

if __name__ == '__main__':
    unittest.main()
