# coding: utf-8

"""
    RMA Service

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v1
    Contact: info@gemini-commerce.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from rma.models.rma_confirm_return_approve_items_request_item import RmaConfirmReturnApproveItemsRequestItem

class TestRmaConfirmReturnApproveItemsRequestItem(unittest.TestCase):
    """RmaConfirmReturnApproveItemsRequestItem unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RmaConfirmReturnApproveItemsRequestItem:
        """Test RmaConfirmReturnApproveItemsRequestItem
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RmaConfirmReturnApproveItemsRequestItem`
        """
        model = RmaConfirmReturnApproveItemsRequestItem()
        if include_optional:
            return RmaConfirmReturnApproveItemsRequestItem(
                grn = '',
                quantity = ''
            )
        else:
            return RmaConfirmReturnApproveItemsRequestItem(
                grn = '',
                quantity = '',
        )
        """

    def testRmaConfirmReturnApproveItemsRequestItem(self):
        """Test RmaConfirmReturnApproveItemsRequestItem"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
