# coding: utf-8

"""
    RMA Service

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v1
    Contact: info@gemini-commerce.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from rma.models.rma_list_notes_by_return_id_request import RmaListNotesByReturnIdRequest

class TestRmaListNotesByReturnIdRequest(unittest.TestCase):
    """RmaListNotesByReturnIdRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RmaListNotesByReturnIdRequest:
        """Test RmaListNotesByReturnIdRequest
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RmaListNotesByReturnIdRequest`
        """
        model = RmaListNotesByReturnIdRequest()
        if include_optional:
            return RmaListNotesByReturnIdRequest(
                tenant_id = '',
                return_id = '',
                page_size = 56,
                page_token = '',
                sorts = [
                    rma.models.rma_list_notes_by_return_id_request_sort.rmaListNotesByReturnIdRequestSort(
                        evaluation_order = 56, 
                        field = 'UNKNOWN', 
                        order = 'DESC', )
                    ]
            )
        else:
            return RmaListNotesByReturnIdRequest(
                tenant_id = '',
                return_id = '',
        )
        """

    def testRmaListNotesByReturnIdRequest(self):
        """Test RmaListNotesByReturnIdRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
