# coding: utf-8

"""
    RMA Service

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v1
    Contact: info@gemini-commerce.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from rma.models.order_data_total_code import OrderDataTotalCode

class TestOrderDataTotalCode(unittest.TestCase):
    """OrderDataTotalCode unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testOrderDataTotalCode(self):
        """Test OrderDataTotalCode"""
        # inst = OrderDataTotalCode()

if __name__ == '__main__':
    unittest.main()
