# coding: utf-8

"""
    RMA Service

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v1
    Contact: info@gemini-commerce.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from rma.models.rma_approve_return_request import RmaApproveReturnRequest

class TestRmaApproveReturnRequest(unittest.TestCase):
    """RmaApproveReturnRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RmaApproveReturnRequest:
        """Test RmaApproveReturnRequest
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RmaApproveReturnRequest`
        """
        model = RmaApproveReturnRequest()
        if include_optional:
            return RmaApproveReturnRequest(
                tenant_id = '',
                id = '',
                refund_shipping_cost = True,
                refund_payment_cost = True,
                items = [
                    rma.models.rma_approve_return_request_item.rmaApproveReturnRequestItem(
                        grn = '', 
                        quantity = '', )
                    ]
            )
        else:
            return RmaApproveReturnRequest(
                tenant_id = '',
                id = '',
                refund_shipping_cost = True,
                refund_payment_cost = True,
                items = [
                    rma.models.rma_approve_return_request_item.rmaApproveReturnRequestItem(
                        grn = '', 
                        quantity = '', )
                    ],
        )
        """

    def testRmaApproveReturnRequest(self):
        """Test RmaApproveReturnRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
