# coding: utf-8

"""
    RMA Service

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v1
    Contact: info@gemini-commerce.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from rma.models.rma_set_received_items_request import RmaSetReceivedItemsRequest

class TestRmaSetReceivedItemsRequest(unittest.TestCase):
    """RmaSetReceivedItemsRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RmaSetReceivedItemsRequest:
        """Test RmaSetReceivedItemsRequest
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RmaSetReceivedItemsRequest`
        """
        model = RmaSetReceivedItemsRequest()
        if include_optional:
            return RmaSetReceivedItemsRequest(
                tenant_id = '',
                id = '',
                items = [
                    rma.models.rma_set_received_items_request_item.rmaSetReceivedItemsRequestItem(
                        grn = '', 
                        quantity = '', )
                    ]
            )
        else:
            return RmaSetReceivedItemsRequest(
                tenant_id = '',
                id = '',
                items = [
                    rma.models.rma_set_received_items_request_item.rmaSetReceivedItemsRequestItem(
                        grn = '', 
                        quantity = '', )
                    ],
        )
        """

    def testRmaSetReceivedItemsRequest(self):
        """Test RmaSetReceivedItemsRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
