# coding: utf-8

"""
    RMA Service

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v1
    Contact: info@gemini-commerce.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from rma.models.rma_list_returns_request import RmaListReturnsRequest

class TestRmaListReturnsRequest(unittest.TestCase):
    """RmaListReturnsRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RmaListReturnsRequest:
        """Test RmaListReturnsRequest
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RmaListReturnsRequest`
        """
        model = RmaListReturnsRequest()
        if include_optional:
            return RmaListReturnsRequest(
                tenant_id = '',
                page_size = 56,
                page_token = '',
                sorts = [
                    rma.models.rma_list_returns_request_sort.rmaListReturnsRequestSort(
                        evaluation_order = 56, 
                        field = 'UNKNOWN', 
                        order = 'DESC', )
                    ],
                filter_mask = '',
                filter = rma.models.list_returns_request_filter.ListReturnsRequestFilter(
                    search_terms = [
                        ''
                        ], 
                    return_ids = [
                        ''
                        ], 
                    return_status = [
                        ''
                        ], 
                    order_grns = [
                        ''
                        ], 
                    order_numbers = [
                        ''
                        ], 
                    order_item_grns = [
                        ''
                        ], 
                    order_item_skus = [
                        ''
                        ], 
                    customer_grns = [
                        ''
                        ], 
                    customer_emails = [
                        ''
                        ], 
                    created_at_start = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    created_at_end = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), )
            )
        else:
            return RmaListReturnsRequest(
                tenant_id = '',
        )
        """

    def testRmaListReturnsRequest(self):
        """Test RmaListReturnsRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
