# coding: utf-8

"""
    RMA Service

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v1
    Contact: info@gemini-commerce.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from rma.models.rma_delete_note_request import RmaDeleteNoteRequest

class TestRmaDeleteNoteRequest(unittest.TestCase):
    """RmaDeleteNoteRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RmaDeleteNoteRequest:
        """Test RmaDeleteNoteRequest
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RmaDeleteNoteRequest`
        """
        model = RmaDeleteNoteRequest()
        if include_optional:
            return RmaDeleteNoteRequest(
                tenant_id = '',
                id = ''
            )
        else:
            return RmaDeleteNoteRequest(
                tenant_id = '',
                id = '',
        )
        """

    def testRmaDeleteNoteRequest(self):
        """Test RmaDeleteNoteRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
