# coding: utf-8

"""
    RMA Service

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v1
    Contact: info@gemini-commerce.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from rma.models.rma_list_returns_request_sort_sort_field import RmaListReturnsRequestSortSortField

class TestRmaListReturnsRequestSortSortField(unittest.TestCase):
    """RmaListReturnsRequestSortSortField unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testRmaListReturnsRequestSortSortField(self):
        """Test RmaListReturnsRequestSortSortField"""
        # inst = RmaListReturnsRequestSortSortField()

if __name__ == '__main__':
    unittest.main()
