# coding: utf-8

"""
    RMA Service

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v1
    Contact: info@gemini-commerce.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from rma.models.rma_list_notes_by_return_id_request_sort_sort_field import RmaListNotesByReturnIdRequestSortSortField

class TestRmaListNotesByReturnIdRequestSortSortField(unittest.TestCase):
    """RmaListNotesByReturnIdRequestSortSortField unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testRmaListNotesByReturnIdRequestSortSortField(self):
        """Test RmaListNotesByReturnIdRequestSortSortField"""
        # inst = RmaListNotesByReturnIdRequestSortSortField()

if __name__ == '__main__':
    unittest.main()
