# coding: utf-8

"""
    RMA Service

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v1
    Contact: info@gemini-commerce.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from rma.models.rma_order_data_item import RmaOrderDataItem

class TestRmaOrderDataItem(unittest.TestCase):
    """RmaOrderDataItem unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RmaOrderDataItem:
        """Test RmaOrderDataItem
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RmaOrderDataItem`
        """
        model = RmaOrderDataItem()
        if include_optional:
            return RmaOrderDataItem(
                id = '',
                product_grn = '',
                qty_ordered = 56,
                qty_committed = 56,
                qty_shipped = 56,
                unit_sale_price = rma.models.rma_money.rmaMoney(
                    units = '', 
                    micros = 56, ),
                unit_list_price = rma.models.rma_money.rmaMoney(
                    units = '', 
                    micros = 56, ),
                unit_vat_amount = rma.models.rma_money.rmaMoney(
                    units = '', 
                    micros = 56, ),
                row_sale_price = rma.models.rma_money.rmaMoney(
                    units = '', 
                    micros = 56, ),
                row_list_price = rma.models.rma_money.rmaMoney(
                    units = '', 
                    micros = 56, ),
                row_vat_amount = rma.models.rma_money.rmaMoney(
                    units = '', 
                    micros = 56, ),
                vat_percentage = 1.337,
                vat_inaccurate = True,
                vat_calculated = True,
                product_name = '',
                product_code = '',
                product_sku = '',
                product_options = '',
                product_img = '',
                product_data = '',
                shipment_info_reference = '',
                promotion_grn = [
                    ''
                    ],
                product_is_virtual = True
            )
        else:
            return RmaOrderDataItem(
        )
        """

    def testRmaOrderDataItem(self):
        """Test RmaOrderDataItem"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
