# coding: utf-8

"""
    RMA Service

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v1
    Contact: info@gemini-commerce.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from rma.models.rma_list_notes_by_return_id_response import RmaListNotesByReturnIdResponse

class TestRmaListNotesByReturnIdResponse(unittest.TestCase):
    """RmaListNotesByReturnIdResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RmaListNotesByReturnIdResponse:
        """Test RmaListNotesByReturnIdResponse
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RmaListNotesByReturnIdResponse`
        """
        model = RmaListNotesByReturnIdResponse()
        if include_optional:
            return RmaListNotesByReturnIdResponse(
                notes = [
                    rma.models.rma_note_response.rmaNoteResponse(
                        id = '', 
                        grn = '', 
                        author = '', 
                        note = '', 
                        created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        deleted_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), )
                    ],
                next_page_token = ''
            )
        else:
            return RmaListNotesByReturnIdResponse(
        )
        """

    def testRmaListNotesByReturnIdResponse(self):
        """Test RmaListNotesByReturnIdResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
