# coding: utf-8

"""
    RMA Service

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v1
    Contact: info@gemini-commerce.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class OrderDataSubtotalCode(str, Enum):
    """
     - ITEMS: gross discount items amount.  - ITEMS_DISCOUNTED: discounted items amount.  - DISCOUNT: discount amount. It is a NEGATIVE amount.
    """

    """
    allowed enum values
    """
    UNKNOWN = 'UNKNOWN'
    PAYMENT = 'PAYMENT'
    SHIPMENT = 'SHIPMENT'
    TAX = 'TAX'
    ITEMS = 'ITEMS'
    ITEMS_DISCOUNTED = 'ITEMS_DISCOUNTED'
    DISCOUNT = 'DISCOUNT'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of OrderDataSubtotalCode from a JSON string"""
        return cls(json.loads(json_str))


