# coding: utf-8

"""
    RMA Service

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v1
    Contact: info@gemini-commerce.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from typing import Any, ClassVar, Dict, List, Optional
from pydantic import BaseModel, StrictBool, StrictStr
from pydantic import Field
from rma.models.rma_customer_info import RmaCustomerInfo
from rma.models.rma_order_data import RmaOrderData
from rma.models.rma_postal_address import RmaPostalAddress
from rma.models.rma_refund_method import RmaRefundMethod
from rma.models.rma_return_history import RmaReturnHistory
from rma.models.rma_return_product import RmaReturnProduct
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class RmaReturnResponse(BaseModel):
    """
    RmaReturnResponse
    """ # noqa: E501
    id: Optional[StrictStr] = None
    grn: Optional[StrictStr] = None
    order_grn: Optional[StrictStr] = Field(default=None, alias="orderGrn")
    status: Optional[StrictStr] = None
    products: Optional[List[RmaReturnProduct]] = None
    preferred_refund_method: Optional[RmaRefundMethod] = Field(default=None, alias="preferredRefundMethod")
    refund_shipping_cost: Optional[StrictBool] = Field(default=None, alias="refundShippingCost")
    refund_payment_cost: Optional[StrictBool] = Field(default=None, alias="refundPaymentCost")
    customer_info: Optional[RmaCustomerInfo] = Field(default=None, alias="customerInfo")
    return_address: Optional[RmaPostalAddress] = Field(default=None, alias="returnAddress")
    note: Optional[StrictStr] = None
    history: Optional[List[RmaReturnHistory]] = None
    created_at: Optional[datetime] = Field(default=None, alias="createdAt")
    updated_at: Optional[datetime] = Field(default=None, alias="updatedAt")
    order_data: Optional[RmaOrderData] = Field(default=None, alias="orderData")
    __properties: ClassVar[List[str]] = ["id", "grn", "orderGrn", "status", "products", "preferredRefundMethod", "refundShippingCost", "refundPaymentCost", "customerInfo", "returnAddress", "note", "history", "createdAt", "updatedAt", "orderData"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of RmaReturnResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in products (list)
        _items = []
        if self.products:
            for _item in self.products:
                if _item:
                    _items.append(_item.to_dict())
            _dict['products'] = _items
        # override the default output from pydantic by calling `to_dict()` of customer_info
        if self.customer_info:
            _dict['customerInfo'] = self.customer_info.to_dict()
        # override the default output from pydantic by calling `to_dict()` of return_address
        if self.return_address:
            _dict['returnAddress'] = self.return_address.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in history (list)
        _items = []
        if self.history:
            for _item in self.history:
                if _item:
                    _items.append(_item.to_dict())
            _dict['history'] = _items
        # override the default output from pydantic by calling `to_dict()` of order_data
        if self.order_data:
            _dict['orderData'] = self.order_data.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of RmaReturnResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "grn": obj.get("grn"),
            "orderGrn": obj.get("orderGrn"),
            "status": obj.get("status"),
            "products": [RmaReturnProduct.from_dict(_item) for _item in obj.get("products")] if obj.get("products") is not None else None,
            "preferredRefundMethod": obj.get("preferredRefundMethod"),
            "refundShippingCost": obj.get("refundShippingCost"),
            "refundPaymentCost": obj.get("refundPaymentCost"),
            "customerInfo": RmaCustomerInfo.from_dict(obj.get("customerInfo")) if obj.get("customerInfo") is not None else None,
            "returnAddress": RmaPostalAddress.from_dict(obj.get("returnAddress")) if obj.get("returnAddress") is not None else None,
            "note": obj.get("note"),
            "history": [RmaReturnHistory.from_dict(_item) for _item in obj.get("history")] if obj.get("history") is not None else None,
            "createdAt": obj.get("createdAt"),
            "updatedAt": obj.get("updatedAt"),
            "orderData": RmaOrderData.from_dict(obj.get("orderData")) if obj.get("orderData") is not None else None
        })
        return _obj


